# Generated by project-harness. Review before editing.
# project-harness: managed-file
# These recipes wrap the existing Chatmux build surface without changing it.

set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

doctor:
    cargo run -p xtask -- check-tools

bootstrap:
    cargo fetch
    cargo fetch --manifest-path chatmux-ui/Cargo.toml

backend-check:
    cargo check --workspace

frontend-check:
    cargo check --manifest-path chatmux-ui/Cargo.toml --target wasm32-unknown-unknown

wasm-check:
    cargo check --target wasm32-unknown-unknown \
      -p chatmux-core \
      -p chatmux-adapter-gpt \
      -p chatmux-adapter-gemini \
      -p chatmux-adapter-grok \
      -p chatmux-adapter-claude

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all --check

lint:
    cargo clippy --workspace --all-targets -- -D warnings

test:
    cargo test --workspace

ui-build:
    cd chatmux-ui && if command -v trunk >/dev/null 2>&1; then env -u NO_COLOR -u CLICOLOR -u CLICOLOR_FORCE trunk build; else env -u NO_COLOR -u CLICOLOR -u CLICOLOR_FORCE "$HOME/.cargo/bin/trunk" build; fi

ui-build-release:
    cd chatmux-ui && if command -v trunk >/dev/null 2>&1; then env -u NO_COLOR -u CLICOLOR -u CLICOLOR_FORCE trunk build --release; else env -u NO_COLOR -u CLICOLOR -u CLICOLOR_FORCE "$HOME/.cargo/bin/trunk" build --release; fi

dist-chrome:
    cargo run -p xtask -- dist chrome

dist-firefox:
    cargo run -p xtask -- dist firefox

package-chrome:
    cargo run -p xtask -- package chrome

package-firefox:
    cargo run -p xtask -- package firefox

package-all:
    cargo run -p xtask -- package-all

clean:
    cargo clean
    cargo run -p xtask -- clean
    rm -rf chatmux-ui/dist

ci: fmt-check lint test frontend-check wasm-check ui-build-release
